# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7ec55b067e986b08e7b3cd62dddbe6443fd1c2cbc1d33de4fdb56a979986d68ba4352c48825e29ed54281a9a0a77c888926f55bc9fb7f6033a861c3b049bcab5

test:
  secret_key_base: c7bb1239934a786d694d4f828611d83ce44d9be7d8e13fc0bdf8e06fca48e8af8157089b6f5f984d8e56c592e21d0ab39c75567c63cff9176e6f44cdec33d108

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
